//CLICKACTIONS1
DZE_CLICK_ACTIONS_ENABLE = true;
//CLICKACTIONS2

//Safezone1
DZE_SAFEZONE_ENABLE = false;
//Safezone2

//PLOTPROTECTION1
DZE_PLOTPROTECTION_ENABLE = false;
//PLOTPROTECTION2

//BASEJUMP1
DZE_BASEJUMP_ENABLE = false;
//BASEJUMP2

//LIFTANDTOW1
DZE_LIFTANDTOW_ENABLE = false;
//LIFTANDTOW2

//REFUEL1
DZE_REFUEL_ENABLE = false;
//REFUEL2

//SELFBLOOD1
DZE_SELFBLOOD_ENABLE = false;
//SELFBLOOD2

//SERVICEPOINT1
DZE_SERVICEPOINT_ENABLE = false;
//SERVICEPOINT2

//REGEN1
DZE_REGEN_ENABLE = false;
//REGEN2

//DEPLOYVEHICLE1
DZE_DEPLOYVEHICLE_ENABLE = false;
//DEPLOYVEHICLE2

//SUICIDE1
DZE_SUICIDE_ENABLE = false;
//SUICIDE2

//VIEWDISTANCE1
DZE_VIEWDISTANCE_ENABLE = false;
//VIEWDISTANCE2
